---
- hosts: windows
  gather_facts: no
  tasks:
  - name: Ensure Application Pool Exist
    win_iis_webapppool:
      name: "{{appPool}}"
      state: present
    register: appPoolExist
    
  - debug:
      var: appPoolExist
      verbosity: 2
