---
- hosts: windows
  gather_facts: no
  tasks:
  - name: Ensure Application Pool Exist
    win_iis_webapppool:
      name: "{{appPool}}"
      state: present
    register: appPoolExist
    
  - debug:
      var: appPoolExist
      verbosity: 2

  - name: Ensure WebSite Exist
    win_iis_website:
      name: "{{appSite}}"
      state: present
    register: siteExist
    
  - debug:
      var: siteExist
      verbosity: 2
