name: PR Lint
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Pr Title
          uses: deepakputhraya/action-pr-title@master
          id: findPr
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - run: echo "Your PR is ${PR}"
          env:
            PR: ${{ steps.findPr.outputs }}
