name: Merge PR
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  merge-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "Merged ${{github.event.pull_request.merged}}"
