name: Jenkins-Integration
on:
  pull_request:
    types: [opened, edited]
jobs:
  Jenkins-Integration:
    runs-on: ubuntu-latest
    steps:
        - name: WebApp Application
          if: startsWith( github.event.pull_request.title, 'webapp' )
          env:
            appName: "webapp"
            branchBase: ${{ github.base_ref }}
          run: |
              echo "Your Application is - ${appName} and Branch is ${branchBase}"
              echo "::set-env name=appName::${appName}"
              echo "::set-env name=branchBase::${branchBase}"
        - name: Messaging Application
          if: startsWith( github.event.pull_request.title, 'messaging' )
          env:
            appName: "messaging"
            branchBase: ${{ github.base_ref }}
          run: |
              echo "Your Application is - ${appName} and Branch is ${branchBase}"
              echo "::set-env name=appName::${appName}"
              echo "::set-env name=branchBase::${branchBase}"
        - name: Business-Api Application
          if: startsWith( github.event.pull_request.title, 'business' )
          env:
            appName: "business"
            branchBase: ${{ github.base_ref }}
          run: |
              echo "Your Application is - ${appName} and Branch is ${branchBase}"
              echo "::set-env name=appName::${appName}"
              echo "::set-env name=branchBase::${branchBase}"
        - name: Trigger Jenkins
          if: ${{ env.appName }}
          uses: docker://l3andro4mc/jenkins-action-parametrized:v1.0
          env: 
            params: "AppName=${{ env.appName }}&BranchName=${{ env.branchBase }}"
            job: "job/Moip-Parent/job/webapp-test/":  
          with:
            args: ${{ secrets.JENKINSURL }} ${{ secrets.JENKINSUSERID }} ${{ secrets.JENKINSUSERTOKEN }} ${{ env.job }} ${{ env.params }} 
