name: WebApp
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
        - name: WebApp Application
          if: startsWith( github.event.pull_request.title, 'webapp' )
          env:
            prTitle: ${{ github.event.pull_request.title }}
          run: echo "Your Application is - ${prTitle} and Branch is ${GITHUB_REF##*/}"
