name: PR Lint
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Pr Title
          uses: jwalton/gh-find-current-pr@v1
          id: findPr
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: OutPut Pr Result
          run: echo "Your PR is ${{ PR }}"
          env:
            PR: ${{ steps.findPr.outputs.title }}
